### ISSUE TITLE
Some kind of "under construction" notice?

### ISSUE THREAD

**Issue by sustained** [dobromir-hristov/vuecommunity#102]
- Some pages (e.g. Nuxt) comprise of only bullet points
- Others are empty or have empty sections (e.g. Legacy; Hosting - Digital Ocean)

Inspired by Wikipedia, I propose a very simple component that shows a little notice stating that:

- the page needs to be worked on
- any help is appreciated
- simply links to the repository (perhaps also the Discord channel?)

Additionally, the same component (presumably with a different icon/colour, for purposes of differentiation) could be used for sections which merely require some expansion or development.

Would this be an acceptable PR to undertake?

**Comment by dobromir-hristov** [comment]
It's on the todo list bud :) thanks for caring.

**Comment by dobromir-hristov** [comment]
It's on the todo list bud :) thanks for caring.

**Comment by sustained** [comment]
My bad, I should have checked all the issues.

**Comment by sustained** [comment]
#68
