### ISSUE TITLE
Vue 3 related

### ISSUE THREAD

**Issue by dobromir-hristov** [dobromir-hristov/vuecommunity#104]
It would be awesome if we have a section with Vue 3 related topics and articles.
More and more people are interested in the differences and upgrades it will bring. I think it would be awesome if we could aggregate all the nice articles into one place.

Format I imagine:
1. A few short sentences on what Vue 3 brings most to the table
2. Then we start with top features:
   1. Links to articles, 
   2. RFC-s (explain briefly what these are) and so on. 

Lots have been written on the topic, so we can collect lots of good info.

**Comment by sustained** [comment]
I made a start.

# Official Repositories

- [Vue 2 Composition API Plugin](https://github.com/vuejs/composition-api) ![](https://img.shields.io/badge/official-green)
- [Vue 3 pre-alpha](https://github.com/vuejs/vue-next) ![](https://img.shields.io/badge/official-green)
- [Vue RFCs repository](https://github.com/vuejs/rfcs) ![](https://img.shields.io/badge/official-green)

# Libraries/Frameworks & Plugins/Addons

- [Automatically Typed, Modular and lightweight Store for Vue using the composition api with DevTools support](https://github.com/posva/pinia) ![](https://img.shields.io/badge/posva-Core%20Team-green)
- [Promises using vue composition api](https://github.com/posva/vue-compose-promise) ![](https://img.shields.io/badge/posva-Core%20Team-green)
- [A Vue.js composition API function to validate forms](https://github.com/logaretm/vue-use-form)
- [Web APIs implemented as Vue.js composition functions](https://github.com/logaretm/vue-use-web)
- [Vue composition-api composable components](https://github.com/pikax/vue-composable)
- [Collection of essential Vue Composition API utils works for Vue 2.x and 3.x](https://github.com/antfu/vueuse)

# RFCs & Docs

- [Vue 3 Composition API RFC](https://vue-composition-api-rfc.netlify.com/) ![](https://img.shields.io/badge/official-green)

# Courses

- [Vue 3 Essentials](https://www.vuemastery.com/courses/vue-3-essentials/why-the-composition-api/)

# Articles & Tutorials

- [Exciting new features in Vue 3](https://vueschool.io/articles/vuejs-tutorials/exciting-new-features-in-vue-3/)
- [Trying the Composition API in Vue 3](https://dev.to/dasdaniel/composition-api-in-vue3-2ob6)
- [Thought on Vue 3 Composition API - `reactive()` considered harmful](https://dev.to/ycmjason/thought-on-vue-3-composition-api-reactive-considered-harmful-j8c) ![](https://img.shields.io/badge/Jason%20Wu-Core%20Team-green)
- [Evan You previews VueJS 3.0](https://medium.com/vue-mastery/evan-you-previews-vue-js-3-0-ab063dec3547)

# Talks
[Design Principals of Vue 3.0 by Evan You](https://www.youtube.com/watch?v=WLpLYhnGqPA) ![](https://img.shields.io/badge/Evan%20You-Core%20Team-green)
[Evan You on What's coming in Vue 3.0](https://www.youtube.com/watch?v=8Hgt9HYaCDA) ![](https://img.shields.io/badge/Evan%20You-Core%20Team-green)

# Demos/Examples & Starters/Boilerplates

- [Minimal webpack setup for Vue 3 (alpha)](https://codesandbox.io/s/github/lbogdan/vue-next-webpack-preview)
- [Tab inject/provide example](https://codesandbox.io/s/tab-inject-provide-composition-api-lkytn)

# Other Resources

- [Vue 3 Cheatsheet](https://www.vuemastery.com/vue-3-cheat-sheet/)

**Comment by dobromir-hristov** [comment]
This looks good. We can use it as a starter. I can write some introduction text.

**Comment by sustained** [comment]
Okay awesome, I was thinking about tackling it myself but I lack (any) experience with Vue 3, so I figured I'd do this instead.

I can however keep searching for other high-quality resources we could add.
