### ISSUE TITLE
Testing learning resources

### ISSUE THREAD

**Issue by dobromir-hristov** [dobromir-hristov/vuecommunity#118]
A list of best learning resources for testing Vue Apps or modern FE in general.

- https://github.com/NoriSte/ui-testing-best-practices - A collection of best practices and tips when testing UI.
- https://lmiller1990.github.io/vue-testing-handbook/ - A short and focused guide on testing Vue apps with Vue Test Utils.
- https://vue-test-utils.vuejs.org/guides/ - the official Vue Test Utils guides. They are full of tips
- https://jrsinclair.com/articles/2016/gentle-introduction-to-javascript-tdd-intro/ - a very nicely written introduction to testing in general
- https://www.manning.com/books/testing-vue-js-applications - One of the first books about testing Vue applications, written by the Vue Test Utils author.
- https://afontcu.dev/ - A very well written blog, full of testing tips.

**Comment by lbogdan** [comment]
- [Test Driven Development in Vue with Cypress by Josh Justice](https://www.youtube.com/watch?v=MU7K_V6rFjM) - very good talk on testing (you can ignore the Cypress part - although Cypress is awesome 😎 -, it's just an "implementation detail", and focus on the concepts and principles)

**Comment by afontcu** [comment]
Thanks for the mention (and the kind words)! :)

Some links that might suit your needs:

[Static vs Unit vs Integration vs E2E Testing for Frontend Apps](https://kentcdodds.com/blog/unit-vs-integration-vs-e2e-tests) code examples are written in React, but they are easy to follow(?)
[Testing API calls in Vue applications](https://afontcu.dev/testing-api-calls/) (disclaimer: I wrote this post).
[Front-end Testing and a tale of three users](https://afontcu.dev/frontend-testing-code-consumers/) (disclaimer: I wrote this post). video version [here](https://www.youtube.com/watch?v=WCUnN9naAPk).

**Comment by dobromir-hristov** [comment]
Done.
