### ISSUE TITLE
Non-English content

### ISSUE THREAD

**Issue by afontcu** [dobromir-hristov/vuecommunity#12]
Hi! First of all, thank you for your hard work! 

After reading the guide, I noticed that no non-English content is available. I believe there's a lot of great content out there written in other languages, too, and it might be great to link it from the guide.

For instance, this [introduction to Vue book](https://jdonsan.gitbooks.io/desarrolla-aplicaciones-con-vuejs/content/) written in Spanish is well-written and informative.

Should there be a place for such kind of content? Should it be collocated with other similar content? Or it'd be better to create a "Multilingual" root menu element, and gather all content there?

---

The guide looks great and I feel it adds a ton of value to both newcomers and well established people. Keep up the good work! 🙌

**Comment by dobromir-hristov** [comment]
This is a very good point. There are translations of books and stuff, that I frankly am not sure how to proceed with. 

Lets do this, we can have a Multilingual Resources page, where we will structure it similar to how the whole website is, as in most cases, the amount of content wont be as much, how does that sound?

**Comment by afontcu** [comment]
Glad you liked the idea!

Putting myself in user's shoes, I'd say it makes sense to collocate content by language and then my category, and not the other way around. Would you agree?

```
Multilingual Resources
  |--- Bulgarian
         |--- Community
         |--- Learning
         |--- Ecosystem
  |--- Spanish
         |--- Community
         |--- Learning
         |--- Ecosystem
```

or


```
Multilingual Resources
  |--- Community
         |--- Bulgarian
         |--- Spanish
  |--- Learning
         |--- Bulgarian
         |--- Spanish
  |--- Ecosystem
         |--- Bulgarian
         |--- Spanish
```

I think I'd go with the former: if I only speak Spanish, I know where to find appropiate content. Otherwise I need to explore each folder and then find whatever I was looking for.

**Comment by dobromir-hristov** [comment]
Now that you mention it, i like the first idea.

I will make a draft and you can push what you have found.

**Comment by dobromir-hristov** [comment]
![](https://i.imgur.com/1221rnd.png)

**Comment by dobromir-hristov** [comment]
@afontcu what do you think? We could even have links to the "in progress" parts of Vue Docs that are being translated, so people can contribute.

**Comment by afontcu** [comment]
Seen and approved! Nice. I'll try to gather interesting resources in Spanish and submit a PR.

Thanks!
