### ISSUE TITLE
Process for listing Vue Formulate on the Handling Forms page?

### ISSUE THREAD

**Issue by andrew-boyd** [dobromir-hristov/vuecommunity#136]
Hello, I'm one of the core maintainers of [Vue Formulate](https://vueformulate.com) and I'd love to have it represented on the page about Handling Forms. We released our 2.0 rewrite 2 months ago along with thorough developer documentation. We're on the cusp of releasing 2.3 which will be our largest feature update to Vue Formulate since the 2.0 release.

What would the proper process be for consideration? Thank you!

**Comment by gustojs** [comment]
Thanks for writing! I'll add it, just let me play with the library first, so that I see what's specific about it in comparison to other options.

Are you on VueLand discord btw? I see Justin is.

**Comment by andrew-boyd** [comment]
Thank you! I am not on the VueLand discord but I’m happy to join if It’s easier to facilitate discussion.

**Comment by gustojs** [comment]
It's not necessary for this exact update but will definitely come handy in the future for collaboration with the rest of the ecosystem.

**Comment by dobromir-hristov** [comment]
Generally you would make a well written, agnostic recap, compare with similar solutions, point a few key differences and why one would pick it and then make a PR and we review.

I guess Gusto is on it though :)

**Comment by andrew-boyd** [comment]
@dobromir-hristov Thank you! I steered away from writing my own summary and submitting a PR due to being one of the core maintainers of Vue Formulate. Being truly agnostic would be difficult (and impossible to convince others of) given my familiarity with the library. If @gustojs is willing to take a look and do an independent summary then I'd honestly prefer that approach.
