### ISSUE TITLE
Missing logo in metadata for individual chapters

### ISSUE THREAD

**Issue by gustojs** [dobromir-hristov/vuecommunity#141]
It would be lovely to have the logo show up when we link to chapters on social media or chat platforms. This is how it works at the moment.

https://twitter.com/gustojs/status/1263486612392075271

**Comment by gnclmorais** [comment]
I would like to take this one, I’d love to start helping around a bit. 🙋‍♂️

**Comment by dobromir-hristov** [comment]
This is already added, donno whats wrong - https://github.com/dobromir-hristov/vuecommunity/blob/master/docs/.vuepress/config.js#L138-L139

**Comment by gnclmorais** [comment]
Interesting, [Twitter’s card validator](https://cards-dev.twitter.com/validator) seems to show that everything’s good:
![image](https://user-images.githubusercontent.com/385232/82643694-e510a980-9c07-11ea-99b5-ca161db5f0e2.png)

**Comment by dobromir-hristov** [comment]
Because I just fixed it :)

**Comment by gnclmorais** [comment]
✔️ Test tweet right now:
![image](https://user-images.githubusercontent.com/385232/82643842-299c4500-9c08-11ea-8d32-dc7f18fb3b89.png)

Nice one, @dobromir-hristov!

**Comment by gustojs** [comment]
Thanks. <3
