### ISSUE TITLE
Vue 3 docs and awesome-vue-3 repository

### ISSUE THREAD

**Issue by gustojs** [dobromir-hristov/vuecommunity#149]
Regarding https://vue-community.org/guide/community/vue-3.html

What's the optimal place to put:
https://v3.vuejs.org - it's official but not a repository. Perhaps we could rename official repositories to official resources?
https://github.com/blacksonic/awesome-vue-3 - that's an extensive list of resources that would be good to link and recommend for those looking for more materials.

**Comment by dobromir-hristov** [comment]
I think this page will be temporary, so no need to throw allot of work. Add both links and call it a day.
