### ISSUE TITLE
Learning Platforms

### ISSUE THREAD

**Issue by dobromir-hristov** [dobromir-hristov/vuecommunity#22]
Content is mostly added, we are missing short explanations for:

- [ ] Scotch
- [ ] FE Masters
- [ ] Codecourse
- [ ] Tutsplus
- [ ] Pluralsight

**Comment by peoray** [comment]
I'd like to work on this

**Comment by dobromir-hristov** [comment]
Alright, then look how we explained the previous learning platforms, and give similar ones to the rest. You can link to the top 2-3 Vue courses from each.
Please keep in mind to be none-biased as possible. We cannot have things like, "This is the most awesome service ever", even if it is. We can say "this is a recommended resource" at most.
