### ISSUE TITLE
Discussion: The standarized pattern for Useful links

### ISSUE THREAD

**Issue by dobromir-hristov** [dobromir-hristov/vuecommunity#30]
I am not sure how this will look on pages with only tutorial links.

**Comment by gustojs** [comment]
Let's discuss all the Useful links stuff together.

The pattern I've been following and which I open up for discussion:

```
### Useful links
* [LibraryName documentation]()
* [LibraryName repository]()
* [LibraryName chat on PlatformName]()
* [Tutorial: TutorialName]()
```

I'd go with `documentation` over `docs` and `repository` over `repo`.

Do we want the tutorial author or source there?

**Comment by dobromir-hristov** [comment]
That tutorial link would be quite big in some cases if we add name or source.
But I am ok with proposal

**Comment by dobromir-hristov** [comment]
Proposal from Gusto
```md
### Useful links:
[repository]
[stuff]
#### Tutorials:
[name 1]
[name 2]
```

**Comment by dobromir-hristov** [comment]
I really like how Algolia have panels for showing Links to "How To's" - https://www.algolia.com/doc/guides/managing-results/refine-results/sorting/
![](https://i.gyazo.com/9492bbadedc99ef41527effc670966dd.png)

We can totally do something similar for Links and Tutorials by using a custom component.

```html
<useful-links>
<useful-links-section title="Links">
    <useful-link to="https://google.com/whatever" title="Repository"/>
    <useful-link to="https://google.com/whatever" title="Discord Chat"/>   
  </useful-links-section>
  <useful-links-section title="Tutorials">
    <useful-link to="https://google.com/whatever" title="Awesome tutorial"/>
    <useful-link to="https://google.com/whatever" title="Another tutorial"/>   
  </useful-links-section>
</useful-links>

**Comment by gustojs** [comment]
I like it, let's go with that.

**Comment by dobromir-hristov** [comment]
Pretty much stole some of their styles for now.

![](https://gyazo.com/5d6230525735b7fcf63d0bba2881958b.png) 

The syntax is even simpler, and works with Lists, paragraphs or single items.
I am explicitly using markdown links, as its much easier than using router-view components. Plus these have path resolution check,

```html
<useful-links>
<useful-links-section title="Social">

* [Vue Vixens website](https://vuevixens.org)
* [Vue Vixens chat on Slack](https://slackin-fxsumkvfno.now.sh/)
* [Vue Vixens on Twitter](https://twitter.com/VueVixens)
* [Vue Vixens blog](https://dev.to/vuevixens)

</useful-links-section>
</useful-links>
```

```html
<useful-links>
<useful-links-section title="Social">

[Vue.js forum on Discourse](https://forum.vuejs.org)

</useful-links-section>
</useful-links>
```
