### ISSUE TITLE
Tools- editors, plugins etc

### ISSUE THREAD

**Issue by dobromir-hristov** [dobromir-hristov/vuecommunity#34]
A page dedicated just to Code Editors and the most popular plugins for them.

**Comment by dobromir-hristov** [comment]
- [ ] VSCode description and plugins for it
- [ ] Webstorm description and plugins 
- [ ] ESLint + Prettier setup guides.

**Comment by peoray** [comment]
I'd like to get started with this, at least fill in the page and maybe others can help fill it up

**Comment by justvr** [comment]
I will create a shell for it, so hopefully someone can join...

And I wouldn't say ESLint + Prettier, better saying ESLint + formatter. Prettier seems to don't care about JS frameworks, so let's not give them a shout out ;)
And linting + formatting should be part for any editor setup, not specially divided section.
Argh, you'll see what I mean

**Comment by dobromir-hristov** [comment]
I have started something here. Will push later today and you guys can continue on top of it.
Sorry if you have already prepared something, we can merge them if needed.
