### ISSUE TITLE
Blogs and Articles incomplete

### ISSUE THREAD

**Issue by peoray** [dobromir-hristov/vuecommunity#51]
I'd like to state some issues here:
- I'm not too sure about the name since we aren't listing any article, in particular, might be worth it to just name it Blogs instead of what it is at the moment

- Some of the blogs are incomplete and needs attention

- In the section for the personal blog. I don't understand the format there. Markus Oberlehner is listed there as a level-1 heading and then others are listed inline Are the suppose to be listed inline or also have some text written too?

- I think it is important we don't populate the personal blog section with anybody that has only ever written one or two tutorials on Vue, I think it should only include people who have blogs dedicated to Vue and nothing else or at least write on Vue regularly and have articles > 5

**Comment by dobromir-hristov** [comment]
I agree with all bullets. Wanted to give Markus a special shout out as he writes amazing posts, but then again we cant really do this for every Joe who writes occasionally. 

As for the last point, I also agree. There are many people who write very rarely or if even continue to do, thus its really hard to justify them there. This was a request from @gustojs which I agreed with but it turned out more of a maintenance problem.

The people that are active, can contribute themselves in the list.

**Comment by peoray** [comment]
I second that people that are active should add themselves but then again anyone who has written one article would want to add themselves. There should a filtering process that allows only people with enough and great articles to be on the list

**Comment by dobromir-hristov** [comment]
I am the one who will decide if they will get added, and with one article, tough luck hehe So dont worry there.

**Comment by peoray** [comment]
I'd like to work on this, but having said a lot of things, I'm wondering which is important atm

**Comment by peoray** [comment]
@dobromir-hristov

**Comment by dobromir-hristov** [comment]
* Rename to Blogs
* Personal blogs becomes just a bullet list. We can ask ppl to add descriptions later.
* Those blogs that have just one post for the past year or so we can drop

**Comment by peoray** [comment]
Few things in mind: 
- I'm not sure about Auth0
- What kind of description to write for pusher
- For the personal blogs, is there anyone currently on the link you want to exclude
- I'm adding an additional two persons who have plenty of articles and should be on the list
- Finally, is it necessary to provide text for each person in the personal blog section, I'm voting we skip it

What are your thoughts?

**Comment by dobromir-hristov** [comment]
- skip it
- check if they are still pushing Vue articles. If they are we can see the rough topics they talk about and summarize.
- I dont have anyone particular. 
- sure go ahead.
- no. Adding what they talk about besides vue would be more than enough.
