### ISSUE TITLE
Make quotes darker for accesibility

### ISSUE THREAD

**Issue by gustojs** [dobromir-hristov/vuecommunity#58]
Quotes are super useful and look cool, but the light grey on a white background is not good for accessibility. Let's consider making it darker.

**Comment by dobromir-hristov** [comment]
How does this look ?
![](https://gyazo.com/edd130bb39ad0dc396be4556f77cbdaf.png)

**Comment by dobromir-hristov** [comment]
Also redid the useful links, bit more flatter design now.
![](https://gyazo.com/daa406b5a344ce3d994e6b2267221b5b.png)

**Comment by gustojs** [comment]
Good idea, should be better now. :) But we'll see once the changes are applied, how it looks on whole page.
