### ISSUE TITLE
Add NuxtPress to Static Site Generators section.

### ISSUE THREAD

**Issue by sustained** [dobromir-hristov/vuecommunity#71]
Perhaps [this section](https://vue-community.org/guide/ecosystem/static-site-generators.html) could do with having @nuxt/press added?

It's very new - I don't think most people know it exists yet. But I'm sure it will with time become popular along with Gridsome and VuePress etc.

https://github.com/nuxt/press
https://nuxt.press/

**Comment by dobromir-hristov** [comment]
Yeah totally. Care to give it a go?

**Comment by sustained** [comment]
If this wasn't added already by now then I'll work on it, just have a lot of projects going on at the moment but I'll try to get to it relatively soon.

**Comment by sustained** [comment]
[PR](https://github.com/dobromir-hristov/vuecommunity/pull/101).

**Comment by sustained** [comment]
Closed by #101.
