### ISSUE TITLE
Improve styling for scanning and readability

### ISSUE THREAD

**Issue by davestewart** [dobromir-hristov/vuecommunity#75]
Hello.

I don't want to tread on anyone's toes, but I'd like to make some small tweaks to the styles to make it easier to scan and read information.

I did these just mucking about in DevTools but happy to clone the repo and submit a PR: 

- Lato font throughout
- tighter body line-spacing
- outdented headings, slightly darker
- simplified "Useful links" sections

There are probably other bits which could be improved.

I've screen-shotted some examples below, but happy to give it all a bit of a once over.

### Outdented headings, makes it easier to scan pages:

Original:

![image](https://user-images.githubusercontent.com/132681/63524400-e0418c80-c4f3-11e9-875f-250cf34ce9c2.png)

Proposed: 

![image](https://user-images.githubusercontent.com/132681/63524426-e8013100-c4f3-11e9-9c07-966c024cb5fc.png)

### Useful links, currently a bit heavy:

Original:

![image](https://user-images.githubusercontent.com/132681/63525599-dfa9f580-c4f5-11e9-87e1-00d10abc692e.png)

Proposed:

![image](https://user-images.githubusercontent.com/132681/63525628-e8023080-c4f5-11e9-9c4c-c1332b101cc1.png)

**Comment by dobromir-hristov** [comment]
The useful links went through a few iterations and I dont know what to do with them. Some ppl like the shadows, some ppl said they hate them... The separators inside were there for a reason, as different groups needed clear separation. Maybe we could drop the `li` border lines or something. As for the shadow, I really do not know.

Headings look OK like that. I have not touched the Vuepress styling much, if at all, so yeah. Very nice addition there.

**Comment by davestewart** [comment]
> The useful links went through a few iterations

I noticed on the screenshot on #59 after I posted! Happy to leave that if you feel it's good enough. 

> The separators inside were there for a reason, as different groups needed clear separation

Yeah, I tried to achieve the same with a little more whitespace.

Let me know

**Comment by sustained** [comment]
I like the outdented headings, that's a nice effect. :+1:

**Comment by dobromir-hristov** [comment]
A few examples how colleagues do it:

### Heroku 

![image](https://user-images.githubusercontent.com/9863944/63544262-6d550780-c52d-11e9-97ff-6aaffc6c7a2b.png)
https://devcenter.heroku.com/articles/custom-domains#keep-reading

### Github

![image](https://user-images.githubusercontent.com/9863944/63544319-a3928700-c52d-11e9-9746-ae6a215ecbf7.png)
https://developer.github.com/v3/guides/best-practices-for-integrators/

### Algolia 
My original inspiration, alas was not taken that well :/

![image](https://user-images.githubusercontent.com/9863944/63544812-a93c9c80-c52e-11e9-9479-b9161f00abeb.png)
https://www.algolia.com/doc/guides/managing-results/refine-results/sorting/

If you remember some good example you can post and we could frankestein something together lol.

As for the other styling, you can make a separate PR and we can reiterate there.

Thanks!

**Comment by davestewart** [comment]
> we could frankestein something together lol

Ha! Yes, exactly.

Though I don't think it needs to be too complex TBH, as long as it's clear and clean to the user.

It would be good if all callouts / boxouts had a level of familiarity. Not sure right now how to do  that but happy to have a play.

**Comment by dobromir-hristov** [comment]
Applied some of the changes suggested.
