### ISSUE TITLE
Cisco Security Blocks the site.

### ISSUE THREAD

**Issue by blowsie** [dobromir-hristov/vuecommunity#84]
vue-community.org
![image](https://user-images.githubusercontent.com/308572/63937415-48472400-ca5a-11e9-9627-0d6a65fc67f8.png)

**Comment by dobromir-hristov** [comment]
Website is hosted on Netlify, with domains also managed there. I have no clue how to fix this to be honest 😆

**Comment by blowsie** [comment]
https://support.umbrella.com/hc/en-us/articles/115004584946-How-to-Read-the-Diagnostic-Information-on-Block-Pages

**Comment by blowsie** [comment]
It seems one of these is the problem
> security — Dynamic DNS, Command and Control, Malware, Unauthorized IP Tunnel Access, Newly Seen Domains, Potentially Harmful, DNS Tunneling VPN, Third-party feeds (AMP, ThreatGrid, etc.)

**Comment by blowsie** [comment]
Ive reported as incorrect block
