### ISSUE TITLE
Adding Quasar Framework

### ISSUE THREAD

**Issue by smolinari** [dobromir-hristov/vuecommunity#91]
Hi,

Would you be interested in a PR adding Quasar Framework to the content under Component Frameworks?

Scott

**Comment by dobromir-hristov** [comment]
My apologies, I had not see it missing.... This is so embarrassing :D I am a huge fan hehe 
I have it under Mobile Apps - https://vue-community.org/guide/ecosystem/mobile-apps.html#quasar

Yeah, lets add it. Want to make the PR?

**Comment by smolinari** [comment]
Sure. I'll also update the mobile section. Some of the links are outdated. It will be Monday or Tuesday of next week before I can get it done though. 

Scott

**Comment by rstoenescu** [comment]
Hi, I think it should be added into more sections, like the UI library, desktop apps and SSR.
Green light for Scott to do a PR on these? @dobromir-hristov

**Comment by dobromir-hristov** [comment]
Yeah. I think it can be added, I am just worried that it will have allot of scattered info. But all of them will link to the Quasar website, so it should be fine.

UI lib: as I said, super fine with it. We could add it under material design ?
Desktop: Doesnt it use Electron under the hood? If so, we should state it is a nice wrapper, giving many goodies.
SSR: Yeah, I am fine with that :)

**Comment by rstoenescu** [comment]
UI lib -> material design --- highly customizable
desktop -> yep, uses Electron under the hood
SSR -> has its own engine under the hood through Quasar CLI

Thanks, Dobromir!

**Comment by valasek** [comment]
I started to work on the issue and will prepare the PR.

**Comment by dobromir-hristov** [comment]
It is done already.

**Comment by rstoenescu** [comment]
Thanks, everyone!

**Comment by smolinari** [comment]
Yeah. Sorry I didn't make references to this issue in the PRs. 😊 

Scott
